server:
  port: 80


jianmu:
  engine:
    debug: true
    service:
      register-port: 6666 # 8848
      map:
        hello: dev.jianmu.engine.api.service.impl.HelloServiceImpl
      discoveries:
      - host: localhost
        port: 8848
        weight: 1
spring:
  devtools:
    restart:
      enabled: false
