server:
  port: 80


jianmu:
  engine:
    debug: true
    service:
      register-port: 2333
      map:
        'dev.jianmu.engine.consumer.LocalStateService': dev.jianmu.engine.consumer.LocalStateServiceImpl
      discoveries:
      - host: localhost
        port: 8848

spring:
  devtools:
    restart:
      enabled: false
