server:
  port: 81


jianmu:
  engine:
    debug: true
    service:
      register-port: 8848
      map:
        'dev.jianmu.engine.consumer.LocalStateService': dev.jianmu.engine.consumer.LocalStateServiceImpl
      discoveries:
      - host: localhost
        port: 2333

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jianmu
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  devtools:
    restart:
      enabled: false

logging:
  level:
    dev.jianmu.engine: debug

