server:
  port: 80

jianmu:
  engine:
    debug: true
    service:
      register-port: 2333
      map:
        'dev.jianmu.engine.consumer.LocalStateService': dev.jianmu.engine.consumer.LocalStateServiceImpl
      discoveries:
      - host: localhost
        port: 8848

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jianmu
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  devtools:
    restart:
      enabled: false

logging:
  level:
    dev.jianmu.engine: debug
    dev.jianmu.engine.rpc.codec.CommonDecoder: info
    dev.jianmu.engine.rpc.translate.NettyClientHandler: info
    dev.jianmu.engine.rpc.translate.NettyServerHandler: info
