// 获取最新 transactionId
#GET http://localhost:81/task/register/obtain

POST http://localhost:81/task/register/submit
Content-Type: application/json

{
  "transactionId": 4,
  "type": "dispatch",
  "priority": 100,
  "cron": null,
  "script": ["help", "gogogo"]
}